In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix, roc_curve, auc, roc_auc_score

from almmo0 import ALMMo0

In [19]:
# Read csv
processed_df = pd.read_csv('dataframes/processed_df.csv')

data_iris = load_iris()
X_iris = data_iris.data
Y_iris = data_iris.target

data_breast_cancer = load_breast_cancer()
X_breast_cancer = data_breast_cancer.data
Y_breast_cancer = data_breast_cancer.target

target_column = 'Type'
other_column_names = ['RR interval', 'Signal 1 mean', 'Signal 1 std', 'Signal 1 median', 'Signal 1 mean absolute deviation', 'Signal 1 quantile 25', 'Signal 1 quantile 75', 'Signal 1 iqr', 'Signal 1 peak', 'Signal 1 valley', 'Signal 1 skewness', 'Signal 1 kurtosis', 'Signal 1 entropy', 'Signal 1 psd entropy', 'Signal 1 psd dominant frequency', 'Signal 1 psd dominant magnitude', 
                                     'Signal 2 mean', 'Signal 2 std', 'Signal 2 median', 'Signal 2 mean absolute deviation', 'Signal 2 quantile 25', 'Signal 2 quantile 75', 'Signal 2 iqr', 'Signal 2 peak', 'Signal 2 valley', 'Signal 2 skewness', 'Signal 2 kurtosis', 'Signal 2 entropy', 'Signal 2 psd entropy', 'Signal 2 psd dominant frequency', 'Signal 2 psd dominant magnitude']

# Encode the target variable into numerical values
le = LabelEncoder()
processed_df[target_column] = le.fit_transform(processed_df[target_column])

In [29]:
X = processed_df[other_column_names].to_numpy()
y = processed_df[target_column].to_numpy()

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2)

model = ALMMo0()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Print accuracy, recall, f1-score, and confusion matrix
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('F1-score: ', f1_score(y_test, y_pred, average='weighted'))
print('Confusion matrix: \n', confusion_matrix(y_test, y_pred))
print('Classification report: \n', classification_report(y_test, y_pred))


Accuracy:  0.35118306351183065
Recall:  0.35118306351183065
Precision:  0.34967615425492243
F1-score:  0.3501505907918787
Confusion matrix: 
 [[82 24  3 25 26]
 [31 40 27 27 35]
 [ 5 38 71 18 29]
 [19 28 32 50 32]
 [22 26 44 30 39]]
Classification report: 
               precision    recall  f1-score   support

           0       0.52      0.51      0.51       160
           1       0.26      0.25      0.25       160
           2       0.40      0.44      0.42       161
           3       0.33      0.31      0.32       161
           4       0.24      0.24      0.24       161

    accuracy                           0.35       803
   macro avg       0.35      0.35      0.35       803
weighted avg       0.35      0.35      0.35       803

